use cgmath::{Deg, EuclideanSpace, InnerSpace, Matrix, Matrix3, Matrix4, Point3, SquareMatrix, Vector3, ortho};

use crate::rendering::{camera::OPENGL_TO_WGPU_MATRIX, mesh::Mesh, textures::tex_cords_to_lin, vertex::*};

#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
/// The sun in the scene
pub struct Sun {
    view_proj: [[f32; 4]; 4],
    direction: [f32; 3],
    /// Due to uniforms requiring 16 byte (4 float) spacing, we need to use a
    /// padding field here
    _padding0: u32,
    pub color: [f32; 3],
    /// Ditto
    _padding1: u32,
}


impl Sun {
    pub fn new(direction: [f32; 3], color: [f32; 3]) -> Self {
        Self {
            direction,
            _padding0: 0,
            color,
            _padding1: 0,
            view_proj: cgmath::Matrix4::identity().into(),
        }
    }

    /// Updates the view projection matrix to match the current location of the
    /// light. Mostly generated by ChatGPT.
    pub fn update_view_proj(&mut self, center: Point3<f32>, scene_size: f32) {
        let dir = Vector3::from(self.direction).normalize();

        let distance = scene_size * 2.5;
        let eye = center - (dir * distance);

        let view = Matrix4::look_at_rh(eye, center, Vector3::unit_y());

        let half = scene_size * 0.5;
        let near = 1.0;
        let far  = 2.0 * distance;

        let proj = ortho(-half, half, -half, half, near, far);

        let vp = OPENGL_TO_WGPU_MATRIX * proj * view;
        self.view_proj = vp.into();
    }

    pub fn sun_mesh(&mut self, center: Point3<f32>) -> Mesh {
        let mut mesh = Mesh::new();

        let dir = Vector3::from(self.direction).normalize();
        let sun_pos = center - (dir * 900.0);

        const SUN_SZ: f32 = 50.0;
        let x_f = sun_pos.x - (SUN_SZ / 2.);
        let y_f = sun_pos.y - (SUN_SZ / 2.);
        let z_f = sun_pos.z - (SUN_SZ / 2.);
        let t_x = 9;
        let t_y = 0;
        let block = [-1, -1, -1];

        mesh.verticies = vec![
            Vertex { // BL
                position: [x_f, y_f, z_f],
                texture_cords: tex_cords_to_lin(t_x+1, t_y+1),
                normal: NORMAL_FRONT,
                block,
            },
            Vertex { // TL
                position: [x_f, y_f + SUN_SZ, z_f],
                texture_cords: tex_cords_to_lin(t_x+1, t_y),
                normal: NORMAL_FRONT,
                block,
            },
            Vertex { // BR
                position: [x_f + SUN_SZ, y_f, z_f],
                texture_cords: tex_cords_to_lin(t_x, t_y+1),
                normal: NORMAL_FRONT,
                block,
            },
            Vertex { // TR
                position: [x_f + SUN_SZ, y_f + SUN_SZ, z_f],
                texture_cords: tex_cords_to_lin(t_x, t_y),
                normal: NORMAL_FRONT,
                block,
            },
            Vertex { // BL
                position: [x_f + SUN_SZ, y_f, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x+1, t_y+1),
                normal: NORMAL_BACK,
                block,
            },
            Vertex { // TL
                position: [x_f + SUN_SZ, y_f + SUN_SZ, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x+1, t_y),
                normal: NORMAL_BACK,
                block,
            },
            Vertex { // BR
                position: [x_f, y_f, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x, t_y+1),
                normal: NORMAL_BACK,
                block,
            },
            Vertex { // TR
                position: [x_f, y_f + SUN_SZ, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x, t_y),
                normal: NORMAL_BACK,
                block,
            },
            Vertex { // BL
                position: [x_f, y_f + SUN_SZ, z_f],
                texture_cords: tex_cords_to_lin(t_x+1, t_y+1),
                normal: NORMAL_UP,
                block,
            },
            Vertex { // TL
                position: [x_f, y_f + SUN_SZ, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x+1, t_y),
                normal: NORMAL_UP,
                block,
            },
            Vertex { // BR
                position: [x_f + SUN_SZ, y_f + SUN_SZ, z_f],
                texture_cords: tex_cords_to_lin(t_x, t_y+1),
                normal: NORMAL_UP,
                block,
            },
            Vertex { // TR
                position: [x_f + SUN_SZ, y_f + SUN_SZ, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x, t_y),
                normal: NORMAL_UP,
                block,
            },
            Vertex { // BL
                position: [x_f, y_f, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x+1, t_y+1),
                normal: NORMAL_DOWN,
                block,
            },
            Vertex { // TL
                position: [x_f, y_f, z_f],
                texture_cords: tex_cords_to_lin(t_x+1, t_y),
                normal: NORMAL_DOWN,
                block,
            },
            Vertex { // BR
                position: [x_f + SUN_SZ, y_f, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x, t_y+1),
                normal: NORMAL_DOWN,
                block,
            },
            Vertex { // TR
                position: [x_f + SUN_SZ, y_f, z_f],
                texture_cords: tex_cords_to_lin(t_x, t_y),
                normal: NORMAL_DOWN,
                block,
            },
            Vertex { // BL
                position: [x_f, y_f, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x+1, t_y+1),
                normal: NORMAL_LEFT,
                block,
            },
            Vertex { // TL
                position: [x_f, y_f + SUN_SZ, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x+1, t_y),
                normal: NORMAL_LEFT,
                block,
            },
            Vertex { // BR
                position: [x_f, y_f, z_f],
                texture_cords: tex_cords_to_lin(t_x, t_y+1),
                normal: NORMAL_LEFT,
                block,
            },
            Vertex { // TR
                position: [x_f, y_f + SUN_SZ, z_f],
                texture_cords: tex_cords_to_lin(t_x, t_y),
                normal: NORMAL_LEFT,
                block,
            },
            Vertex { // BL
                position: [x_f + SUN_SZ, y_f, z_f],
                texture_cords: tex_cords_to_lin(t_x+1, t_y+1),
                normal: NORMAL_RIGHT,
                block,
            },
            Vertex { // TL
                position: [x_f + SUN_SZ, y_f + SUN_SZ, z_f],
                texture_cords: tex_cords_to_lin(t_x+1, t_y),
                normal: NORMAL_RIGHT,
                block,
            },
            Vertex { // BR
                position: [x_f + SUN_SZ, y_f, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x, t_y+1),
                normal: NORMAL_RIGHT,
                block,
            },
            Vertex { // TR
                position: [x_f + SUN_SZ, y_f + SUN_SZ, z_f + SUN_SZ],
                texture_cords: tex_cords_to_lin(t_x, t_y),
                normal: NORMAL_RIGHT,
                block,
            },
        ];

        mesh.indicies = vec![
            3, 2, 0,
            3, 0, 1,

            7, 6, 4,
            7, 4, 5,

            11, 10, 8,
            11, 8, 9,

            15, 14, 12,
            15, 12, 13,

            19, 18, 16,
            19, 16, 17,

            23, 22, 20,
            23, 20, 21,
        ];

        mesh
    }
}
