use cgmath::{EuclideanSpace, InnerSpace, Matrix4, Point3, SquareMatrix, Vector3, ortho};

use crate::rendering::camera::OPENGL_TO_WGPU_MATRIX;

#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
/// The sun in the scene
pub struct Sun {
    view_proj: [[f32; 4]; 4],
    direction: [f32; 3],
    /// Due to uniforms requiring 16 byte (4 float) spacing, we need to use a
    /// padding field here
    _padding0: u32,
    pub color: [f32; 3],
    /// Ditto
    _padding1: u32,
}


impl Sun {
    pub fn new(direction: [f32; 3], color: [f32; 3]) -> Self {
        Self {
            direction,
            _padding0: 0,
            color,
            _padding1: 0,
            view_proj: cgmath::Matrix4::identity().into(),
        }
    }

    /// Updates the view projection matrix to match the current location of the
    /// light. Mostly generated by ChatGPT.
    pub fn update_view_proj(&mut self, scene_center: [f32; 3], scene_size: f32) {
        let dir = Vector3::from(self.direction).normalize();
        let center = Point3::from(scene_center);

        let distance = scene_size * 2.5;
        let eye = center - (dir * distance);

        let view = Matrix4::look_at_rh(eye, center, Vector3::unit_y());

        let half = scene_size * 0.5;
        let near = 1.0;
        let far  = 2.0 * distance;

        let proj = ortho(-half, half, -half, half, near, far);

        let vp = OPENGL_TO_WGPU_MATRIX * proj * view;
        self.view_proj = vp.into();
    }

    pub fn get_direction(&self) -> [f32; 3] {
        self.direction
    }

    /// Note that the view projection matrix spat out by this may be inccorect
    /// if either the light's direction or the scene-center position has changed
    /// since the last time `update_view_proj` was called!
    pub fn get_view_proj(&self) -> [[f32; 4]; 4] {
        self.view_proj
    }

    /// Note that this will invalidate the view projection matrix.
    pub fn update_direction(&mut self, new_direction: [f32; 3]) {
        self.direction = new_direction;
    }
}
